[general]
imaging mode = "preview imaging"

[basic params]
X pixel # = 1000.000000    
X pixel size(um) = 0.500000    
Y pixel # = 1000.000000    
Y pixel size(um) = 0.500000    
line rate(Hz) = 500.000000    
stage scan? = TRUE    

[advanced params]
x flyback time(%) = 20.000000    
signal offset = 800.000000    
frame time(s) = 2.072320    
fetch # per frame = 100.000000    
galvo sampling rate = 50000.000000    

[PXI channel]
Vertical Range (V) = 5.000000    
Min Sample Rate = 600000.000000    
# of Channels = 8.000000    
Min Record Length = 2200.000000    
Number Of Records = 500.000000    
Edge Trigger Level (V) = 1.000000
trigger source = "VAL_PFI_1"
Trigger Position(%) = 36.800000    
act Record Length = 2200.000000    
PMT2 # of Channels = 1.000000    

[task plan]
X start = 1.000000    
X end = 3.000000    
X overlap = 0.150000    
Y start = 0.000000    
Y end = 10.000000    
Z start = -0.700000    
Z end = 0.000000    
Z step size = 0.018000    
start scan # = 1.000000    
end scan # = 234.000000    