[basic params]
X pixel # = CtrlType:Digital Default:1024 Min:2 Max:20480 Increment:2
X pixel size(um) = CtrlType:Digital Default:0.5 Min:0 Max:10 Increment:0
Y pixel # = CtrlType:Digital Default:1024 Min:2 Max:204800 Increment:2
Y pixel size(um) = CtrlType:Digital Default:0.5 Min:0 Max:10 Increment:0
line rate(Hz) = CtrlType:Digital Default:500 Min:1 Max:2000 Increment:0
stage scan? = CtrlType:Boolean Default:0 Min:0 Max:1 Increment:0

[advanced params]
x flyback time(%) = CtrlType:Digital Default:15 Min:0 Max:50 Increment:0
signal offset = CtrlType:Digital Default:100 Min:0 Max:10000 Increment:0
frame time(s) = CtrlType:Digital Default:1 Min:0 Max:100 Increment:0.1
fetch # per frame = CtrlType:Digital Default:1 Min:1 Max:1000 Increment:1 
galvo sampling rate = CtrlType:Digital Default:50000 Min:10000 Max:200000 Increment:1 

[PXI channel]
Vertical Range (V) = CtrlType:Digital Default:5 Min:0 Max:10 Increment:0
Min Sample Rate = CtrlType:Digital Default:20000000 Min:0 Max:100000000 Increment:0
Min Record Length = CtrlType:Digital Default:1000 Min:0 Max:10000 Increment:1
Number Of Records = CtrlType:Digital Default:10000 Min:0 Max:1000000 Increment:1
Edge Trigger Level (V) = CtrlType:Digital Default:1 Min:0 Max:5 Increment:0
Trigger Position(%) = CtrlType:Digital Default:50 Min:0 Max:100 Increment:0
act Record Length = CtrlType:Digital Default:1000 Min:0 Max:100000 Increment:1
# of Channels= CtrlType:Digital Default:2 Min:1 Max:8 Increment:1
PMT2 # of Channels= CtrlType:Digital Default:2 Min:1 Max:8 Increment:1

[task plan]
X start = CtrlType:Digital Default:0 Min:-20 Max:20 Increment:0
X end = CtrlType:Digital Default:10 Min:-20 Max:20 Increment:0
Y start = CtrlType:Digital Default:0 Min:-20 Max:20 Increment:0
Y end = CtrlType:Digital Default:10 Min:-20 Max:20 Increment:0
Z start = CtrlType:Digital Default:0 Min:-12 Max:12 Increment:0
Z end = CtrlType:Digital Default:10 Min:-12 Max:12 Increment:0
Z step size = CtrlType:Digital Default:0.002 Min:-10 Max:10 Increment:0
start scan # = CtrlType:Digital Default:1 Min:1 Max:100000 Increment:1
end scan # = CtrlType:Digital Default:100 Min:1 Max:100000 Increment:1

[NI card channels]
frame trigger = PhysicalChannel:PXI1Slot6/ctr0 Max:5 Min:0 Terminal:/PXI1Slot6/PFI2 StartTrigger:/PXI1Slot6/PFI0 ClockSource:NA ScalingFactor:0
digital galvo clock = PhysicalChannel:PXI1Slot6/ctr1 Max:5 Min:0 Terminal:/PXI1Slot6/PFI1 StartTrigger:/PXI1Slot6/PFI2 ClockSource:NA ScalingFactor:0
digital galvo synchonize channel = PhysicalChannel:PXI1Slot6/port0/line0 Max:5 Min:0 Terminal:NA StartTrigger:/PXI1Slot6/PFI2 ClockSource:/PXI1Slot6/PFI1 ScalingFactor:0
x galvo = PhysicalChannel:PXI1Slot6/port0/line1 Max:5 Min:0 Terminal:NA StartTrigger:/PXI1Slot6/PFI2 ClockSource:/PXI1Slot6/PFI1 ScalingFactor:0.005320
y galvo = PhysicalChannel:PXI1Slot6/port0/line2 Max:5 Min:0 Terminal:NA StartTrigger:/PXI1Slot6/PFI2 ClockSource:/PXI1Slot6/PFI1 ScalingFactor:0.004575
line trigger = PhysicalChannel:PXI1Slot6/port0/line3 Max:5 Min:0 Terminal:NA StartTrigger:/PXI1Slot6/PFI2 ClockSource:/PXI1Slot6/PFI1 ScalingFactor:0
line trigger 2 = PhysicalChannel:PXI1Slot6/port0/line4 Max:5 Min:0 Terminal:NA StartTrigger:/PXI1Slot6/PFI2 ClockSource:/PXI1Slot6/PFI1 ScalingFactor:0
line trigger 3 = PhysicalChannel:PXI1Slot6/port0/line5 Max:5 Min:0 Terminal:NA StartTrigger:/PXI1Slot6/PFI2 ClockSource:/PXI1Slot6/PFI1 ScalingFactor:0

[Note]
galvo scan:
frame trigger is auto run

stage scan:
frame trigger is triggered by stage